### PR TITLE
Inject common-utils to alerting

### LINKED ISSUE #1379: IOException: Unknown ConfigType ordinal [11]` in `opensearch-alerting`
##  Problem Description
A runtime exception `IOException: Unknown ConfigType ordinal [11]` occurs within the `opensearch-alerting` plugin when it interacts with the `wazuh-indexer-notifications` plugin.

The error is triggered during the deserialization of the `GetNotificationConfigResponse` over the transport layer.

##  Root Cause Analysis
The issue stems from a **dependency mismatch** in the `common-utils` library bundled with the alerting plugin:

1.  **Wazuh's Fork**: The `wazuh-indexer-notifications` plugin uses a patched version of `common-utils` that introduces a new enum member, `ACTIVE_RESPONSE`, at **ordinal 11** in the `ConfigType` class.
2.  **Upstream Alerting**: The `opensearch-alerting` plugin bundles the standard, unpatched `common-utils-3.5.0.0.jar`. In this version, the `ConfigType` enum only defines ordinals **0–10**.
3.  **The Crash**: Because each plugin uses its own classloader, when `opensearch-alerting` receives a response containing ordinal 11, its local copy of `ConfigType` doesn't recognize it, causing the `IOException`.

### Verification (Internal Environment)
Confirmed by checking the JARs inside the running container:

* **Correct (Notifications)**: `/usr/share/wazuh-indexer/plugins/wazuh-indexer-notifications/common-utils-3.5.0.0-SNAPSHOT.jar` ✅
* **Incorrect (Alerting)**: `/usr/share/wazuh-indexer/plugins/opensearch-alerting/common-utils-3.5.0.0.jar` ❌ (Missing ordinal 11)

---

##  Proposed Solution (Patching the Alerting Plugin)

To resolve this without a full recompilation of the stack, the `common-utils` JAR inside the `opensearch-alerting` directory must be replaced with the patched version.

### Steps to Fix:
1.  **Extract** the patched `common-utils` from the notifications plugin.
2.  **Overwrite** the outdated JAR in the `opensearch-alerting` folder.
3.  **Restart** the service.

```bash
# Extract the patched JAR
unzip -p /usr/share/wazuh-indexer/plugins/wazuh-indexer-notifications/wazuh-indexer-notifications-*.jar common-utils-3.5.0.0-SNAPSHOT.jar > /tmp/patched-common-utils.jar

# Replace the JAR in the alerting plugin directory
cp /tmp/patched-common-utils.jar /usr/share/wazuh-indexer/plugins/opensearch-alerting/common-utils-3.5.0.0.jar

# Restart wazuh-indexer
systemctl restart wazuh-indexer

### PR DESCRIPTION
**Pull request by ferooo23**
### Description

This PR implements a build-time fix for a runtime `IOException: Unknown ConfigType ordinal [11]` that occurs in the `opensearch-alerting` plugin when deserializing transport layer responses from the `wazuh-indexer-notifications` plugin.

### Root Cause

The issue stems from a `common-utils` library version mismatch between plugins:

- **wazuh-indexer-notifications**: bundles a patched `common-utils-3.5.0.0-SNAPSHOT.jar` that introduces a new `ACTIVE_RESPONSE` member at ordinal 11 in the `ConfigType` enum.
- **opensearch-alerting**: bundles the upstream `common-utils-3.5.0.0.jar`, where `ConfigType` only defines ordinals 0–10.

Because each plugin operates under its own classloader, when `opensearch-alerting` receives a `GetNotificationConfigResponse` containing ordinal 11, its local `ConfigType` class cannot deserialize it, throwing an `IOException` and returning HTTP 500 to the caller.

### Changes

 ·**build-scripts/assemble.sh**

During the final `wazuh-indexer` assembly phase, a dependency injection step was added:

1. Locates the pre-compiled patched `common-utils-3.5.0.0-SNAPSHOT.jar` from the `wazuh-indexer-notifications` plugin directory.
2. Overwrites the outdated `common-utils-3.5.0.0.jar` inside the `opensearch-alerting` plugin directory prior to packaging.
3. The resulting `.deb`/`.rpm` distributions ship with a consistent `common-utils` version across both plugins, eliminating the classloader mismatch at runtime.

### Related Issues

Resolves #1379

### Validation

Validated on a single-node Vagrant environment running Wazuh Indexer 5.0.0, installing the built `.deb` package from CI.The fix was verified by comparing the checksums of the `common-utils` JAR across both plugins before and after applying the patch.

**Without patch**: checksums differ, confirming the classloader mismatch:
```bash
sha1sum \
  /usr/share/wazuh-indexer/plugins/opensearch-alerting/common-utils-3.5.0.0.jar \
  /usr/share/wazuh-indexer/plugins/wazuh-indexer-notifications/common-utils-3.5.0.0-SNAPSHOT.jar
```
```
bf79645ebf93a2de935bc828dcf7bbdb4702922b  /usr/share/wazuh-indexer/plugins/opensearch-alerting/common-utils-3.5.0.0.jar
d67190dadc389c39e4dbd9202f2fc2d3b44b3195  /usr/share/wazuh-indexer/plugins/wazuh-indexer-notifications/common-utils-3.5.0.0-SNAPSHOT.jar
```

**With patch**: checksums match, confirming both plugins now share the same `ConfigType` definition:
```bash
sha1sum \
  /usr/share/wazuh-indexer/plugins/opensearch-alerting/common-utils-3.5.0.0.jar \
  /usr/share/wazuh-indexer/plugins/wazuh-indexer-notifications/common-utils-3.5.0.0-SNAPSHOT.jar
```
```
d67190dadc389c39e4dbd9202f2fc2d3b44b3195  opensearch-alerting/common-utils-3.5.0.0.jar
d67190dadc389c39e4dbd9202f2fc2d3b44b3195  wazuh-indexer-notifications/common-utils-3.5.0.0-SNAPSHOT.jar
```

#### Runtime end-to-end validation

Creating an `active_response` notification and verifying that `opensearch-alerting` deserializes it without throwing `IOException: Unknown ConfigType ordinal [11]` is not yet possible in this version. The REST endpoint and server-side integration that would trigger ordinal 11 over the transport layer are pending implementation in wazuh/wazuh#34606.

### CODE REVIEW

File: build-scripts/assemble.sh [hunk 1]
```diff
@@ -250,6 +250,16 @@ function install_plugins() {
 
         OPENSEARCH_PATH_CONF=$PATH_CONF "${PATH_BIN}/opensearch-plugin" install --batch --verbose "file:${plugin_path}"
     done
+
+    echo "Workaround: Injecting modified common-utils JAR to opensearch-alerting"
+    PAT_NOTIF_DIR="${PATH_PLUGINS}/wazuh-indexer-notifications"
+    PAT_ALERT_JAR="${PATH_PLUGINS}/opensearch-alerting/common-utils-3.5.0.0.jar"
+
+    if [ -f "${PAT_NOTIF_DIR}/common-utils-3.5.0.0-SNAPSHOT.jar" ]; then
```
Comment (Jorgesnchz) [inline build-scripts/assemble.sh]: Maybe we could avoid to hardcode the version, but since this is a temporary fix until we fork alerting repo is not a big problem, so I'm approving
