### PR TITLE
Adapt build workflows for dedicated runners and fix arm64 dependencies

### LINKED ISSUE #1339: Dedicated runners for the package builder workflow
## Description

Recently, we have identified that the GH Workflows spend quite some time enqueued before a runner takes the job. To reduce the build time of Wazuh Indexer packages, we have created dedicated GH Runners.

In this issue, we are going to update the GH Workflows to build Wazuh Indexer packages and Docker images to use these dedicated runners.

We have two runner groups available for GitHub Actions:

- wz-linux-amd64
- wz-linux-arm64

Make sure that our GitHub Actions reference the runner group, not a specific runner instance (otherwise we don't take advantage of having multiple ones).

Reference:
- https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#choosing-runners-in-a-group

## Functional requirements

- The `build` job in the package build workflows must run on the dedicated runner group matching the target architecture:
  - `wz-linux-amd64` for `x64` builds.
  - `wz-linux-arm64` for `arm64` builds.
- The `build-and-push-docker-image` job in the Docker workflow must run on the `wz-linux-amd64` dedicated runner group.
- Lightweight jobs (version resolution, compatibility checks, matrix setup, plugin compilation) must continue to run on GitHub-hosted runners (`ubuntu-24.04`), as they do not benefit from dedicated runners.

## Implementation restrictions

- Adhere to GitHub documentation and guidelines for the usage of runner groups.
- Do not modify the package building logic.
- Do not modify the GH Workflows parameters or outputs.
- Only the `runs-on` field of the affected jobs should change.

## Plan

- In `5_builderpackage_indexer.yml`: update the `build` job `runs-on` to use `wz-linux-amd64` for `x64` and `wz-linux-arm64` for `arm64`.
- In `4_builderpackage_indexer.yml`: update the `build` job `runs-on` to use `wz-linux-amd64` for `x64` and `wz-linux-arm64` for `arm64`.
- In `5_builderpackage_docker.yml`: update the `build-and-push-docker-image` job `runs-on` to use `wz-linux-amd64`.

### PR DESCRIPTION
**Pull request by ana-rm**
### Description
This PR optimizes the package build workflows by directing jobs to specific runner groups based on architecture and ensuring all necessary dependencies are met for self-hosted environments.

###Changes
- Modified the build job to use dedicated runner groups
- Added a conditional step to install maven, rpm  and cpio on arm64 runners to fix "command not found" errors.
- Added a specific installation step for docker.io and socket permission configuration when building RPM packages on arm64 architecture.

### Related Issues
Resolves #1339

### CODE REVIEW

File: build-scripts/provision.sh [hunk 1]
```diff
@@ -1,10 +1,64 @@
...
+esac
+
+
+# Arquitecture logic
+# ==========================================
+if [[ "$ARCH" == "aarch64" ]]; then
+    echo "ARM64 detected: Executing architecture-specific commands..."
+
+    # If we are on an ARM64 machine but need to build RPMs/General packages
+    if [[ "$OS_ID" == "ubuntu" || "$OS_ID" == "debian" ]]; then
```
Comment (QU3B1M) [inline build-scripts/provision.sh]: This will only work for `DEB` packages, not `RPM`s, we should cover `RPM` too

**Review by QU3B1M — APPROVED** [review]
